services:
  db-s3-downloader-service:
    image: postgres:17
    container_name: bd_s3_downloader_service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data_new:/var/lib/postgresql/data
    networks:
      - s3_downloader_network

networks:
  s3_downloader_network:
    driver: bridge

volumes:
  db_data_new:
